//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aksyon_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIConfig
    {
        public int id { get; set; }
        public string client_secret { get; set; }
        public Nullable<int> client_id { get; set; }
        public string grant_type { get; set; }
        public string url { get; set; }
    }
}
